from codewars_task.count_ip_adresses_5kuy import print_count_ip_adresses
from codewars_task.merged_string_checker_5kuy import print_merged_string_checker
from codewars_task.valid_parentheses_5kuy import print_valid_parentheses


print_valid_parentheses()
print_count_ip_adresses()
print_merged_string_checker()

